import { mkdirSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { buildProfile } from './profile-data.mjs';

const seed = buildProfile();

mkdirSync(resolve(import.meta.dirname, 'src/data'), { recursive: true });

const output = `// Auto-generated by prebuild.mjs. Do not edit manually.
import type { CandidateProfile } from '../types/profile';

export const seedProfile: CandidateProfile = ${JSON.stringify(seed, null, 2)} as const;
`;

writeFileSync(resolve(import.meta.dirname, 'src/data/seed.ts'), output);
console.log('prebuild: wrote src/data/seed.ts');
