#!/usr/bin/env bash
# JobSeeker / Career-Ops installer
#
# Usage:
#   bash install.sh                 # interactive (asks docker vs local)
#   bash install.sh --docker        # docker-compose path
#   bash install.sh --local         # local Node.js path
#   bash install.sh --update        # pull + apply system updates
#   bash install.sh --uninstall     # tear down (asks confirmation)
#   bash install.sh --doctor        # diagnose environment
#
# After install, opens the dashboard at http://localhost:4747 and lands you
# on the 6-step onboarding wizard: drop your resume → AI confirms basics →
# pick target roles + comp → flag deal-breakers → add narrative → ship.
#
# Exit codes:
#   0  ok
#   1  user declined / cancelled
#   2  missing prerequisite
#   3  installer error

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PORT="${DASHBOARD_PORT:-4747}"
readonly HOST="${DASHBOARD_HOST:-127.0.0.1}"
readonly URL="http://${HOST}:${PORT}"

# ── Colors (no-color when not a TTY or NO_COLOR set) ────────────────────────
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  C_RESET='\033[0m'; C_DIM='\033[2m'; C_BOLD='\033[1m'
  C_BLUE='\033[36m'; C_GREEN='\033[32m'; C_YELLOW='\033[33m'; C_RED='\033[31m'
else
  C_RESET=''; C_DIM=''; C_BOLD=''
  C_BLUE=''; C_GREEN=''; C_YELLOW=''; C_RED=''
fi

log()  { printf "${C_DIM}›${C_RESET} %s\n" "$*"; }
ok()   { printf "${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "${C_YELLOW}⚠${C_RESET} %s\n" "$*" >&2; }
fail() { printf "${C_RED}✗${C_RESET} %s\n" "$*" >&2; exit "${2:-3}"; }

banner() {
  printf "${C_BLUE}${C_BOLD}\n"
  cat <<'EOF'
   ╔═══════════════════════════════════════════╗
   ║        JobSeeker · Career-Ops             ║
   ║   Senior-level AI job-search assistant    ║
   ╚═══════════════════════════════════════════╝
EOF
  printf "${C_RESET}\n"
}

# ── Helpers ─────────────────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }
ask()  {
  local q="$1" def="${2:-}" reply
  if [[ -n "$def" ]]; then
    read -r -p "$(printf "${C_BOLD}? %s [%s]: ${C_RESET}" "$q" "$def")" reply
    echo "${reply:-$def}"
  else
    read -r -p "$(printf "${C_BOLD}? %s: ${C_RESET}" "$q")" reply
    echo "$reply"
  fi
}
yesno() {
  local q="$1" def="${2:-y}" reply
  reply=$(ask "$q (y/n)" "$def")
  [[ "$reply" =~ ^[Yy] ]]
}

open_url() {
  local url="$1"
  if have open;        then open "$url"          # macOS
  elif have xdg-open;  then xdg-open "$url"      # Linux
  elif have wslview;   then wslview "$url"       # WSL
  elif have powershell.exe; then powershell.exe -NoProfile -Command "Start-Process '$url'"  # Windows-from-bash
  else log "Open this URL in your browser: $url"
  fi
}

random_secret() {
  if   have openssl; then openssl rand -hex 32
  elif [[ -r /dev/urandom ]]; then head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  else date +%s%N | sha256sum 2>/dev/null | cut -c1-64 || echo "change-me-$(date +%s)"
  fi
}

# ── Prereqs ─────────────────────────────────────────────────────────────────
require_docker() {
  have docker || fail "Docker is required for --docker mode. Install: https://docs.docker.com/get-docker/" 2
  if docker compose version >/dev/null 2>&1; then
    DC=(docker compose)
  elif have docker-compose; then
    DC=(docker-compose)
    warn "Using legacy docker-compose. Newer 'docker compose' (v2) is preferred."
  else
    fail "docker compose plugin is required. Install: https://docs.docker.com/compose/install/" 2
  fi
}

require_node() {
  have node || fail "Node.js 20+ is required for --local mode. Install: https://nodejs.org" 2
  local ver
  ver=$(node -v | sed -E 's/^v([0-9]+).*/\1/')
  if (( ver < 20 )); then
    fail "Node.js >= 20 required (have v$(node -v)). Use nvm: nvm install 22" 2
  fi
  ok "Node.js $(node -v) detected"
}

# ── .env handling ───────────────────────────────────────────────────────────
ensure_env() {
  cd "$SCRIPT_DIR"
  if [[ -f .env ]]; then
    log ".env exists — keeping current values"
    return
  fi
  if [[ ! -f .env.example ]]; then
    fail ".env.example missing — corrupt checkout?" 3
  fi
  cp .env.example .env
  ok "Created .env from .env.example"

  # Generate a session secret if the example placeholder is still there
  local secret
  secret=$(random_secret)
  if grep -q "^SESSION_SECRET=" .env 2>/dev/null; then
    sed -i.bak "s|^SESSION_SECRET=.*|SESSION_SECRET=${secret}|" .env && rm -f .env.bak
  else
    printf "\n# Auto-generated by install.sh\nSESSION_SECRET=%s\n" "$secret" >> .env
  fi
  ok "Generated SESSION_SECRET"

  warn "Edit .env to add ANTHROPIC_API_KEY (and optionally GMAIL_*) before first eval"
}

# Initialize per-user files from templates so pipeline scripts that append
# to them don't fail on a fresh clone. Each is gitignored — they hold PII.
ensure_user_files() {
  cd "$SCRIPT_DIR"
  if [[ -f templates/story-bank.template.md && ! -f interview-prep/story-bank.md ]]; then
    mkdir -p interview-prep
    cp templates/story-bank.template.md interview-prep/story-bank.md
    ok "Initialized interview-prep/story-bank.md from template"
  fi
  if [[ -f templates/portals.example.yml && ! -f portals.yml ]]; then
    cp templates/portals.example.yml portals.yml
    ok "Initialized portals.yml from template"
  fi
  if [[ -f config/profile.example.yml && ! -f config/profile.yml ]]; then
    cp config/profile.example.yml config/profile.yml
    log "Initialized config/profile.yml from example (you'll fill it via the wizard)"
  fi
  if [[ -f modes/_profile.template.md && ! -f modes/_profile.md ]]; then
    cp modes/_profile.template.md modes/_profile.md
    ok "Initialized modes/_profile.md from template"
  fi
  # Ensure write-target directories exist
  mkdir -p data reports output interview-prep tmp
}

# ── Onboarding nudge ────────────────────────────────────────────────────────
print_onboarding() {
  printf "${C_BOLD}Next: 6-step onboarding wizard${C_RESET}\n"
  cat <<EOF
   1. Drop your resume (.txt / .md or paste)
   2. Confirm basics — name, email, location, headline
   3. Pick target roles + comp range
   4. Flag deal-breakers (optional)
   5. Add narrative — superpowers, best achievement, proof points (optional)
   6. Generate — your CV PDF renders, the pipeline arms

   Open ${C_BLUE}${URL}${C_RESET} → click ${C_BOLD}⊕ Profile${C_RESET} (or press ${C_BOLD}⌘ ,${C_RESET})
EOF
}

# ── Modes ───────────────────────────────────────────────────────────────────
run_docker() {
  require_docker
  ensure_env
  ensure_user_files
  cd "$SCRIPT_DIR"

  log "Building image (first run takes ~3 min for Chromium)…"
  "${DC[@]}" build

  log "Starting container in the background…"
  "${DC[@]}" up -d

  log "Waiting for /api/health…"
  for i in {1..30}; do
    if curl -fsS "${URL}/api/health" >/dev/null 2>&1; then
      ok "Dashboard is up at ${URL}"
      print_onboarding
      open_url "$URL" 2>/dev/null || true
      return 0
    fi
    sleep 1
  done
  warn "Health check didn't pass within 30s — try: ${DC[*]} logs -f"
  return 0
}

run_local() {
  require_node
  ensure_env
  ensure_user_files
  cd "$SCRIPT_DIR"

  log "Installing dependencies (npm install)…"
  npm install --no-audit --no-fund

  log "Running self-tests…"
  if npm test --silent >/dev/null 2>&1; then
    ok "All tests pass"
  else
    warn "Tests not all passing — continuing anyway. Check: npm test"
  fi

  ok "Ready."
  print_onboarding
  printf "\n${C_BOLD}Start the dashboard with:${C_RESET} npm start\n"
  printf "    or in the background: ${C_DIM}npm start &${C_RESET}\n"
  if yesno "Start the dashboard now?" "y"; then
    open_url "$URL" 2>/dev/null || true
    exec node dashboard-web/server.mjs
  fi
}

run_update() {
  cd "$SCRIPT_DIR"
  if [[ -d .git ]]; then
    log "git pull…"
    git pull --ff-only || warn "git pull failed; continuing"
  fi
  if have node; then
    log "Running update-system.mjs apply…"
    node update-system.mjs apply
    ok "System files updated. Your data is untouched."
  else
    warn "Node not found; install it then run: node update-system.mjs apply"
  fi
}

run_uninstall() {
  cd "$SCRIPT_DIR"
  warn "This stops services. Your data (cv.md, config/, data/, reports/) is preserved."
  if ! yesno "Stop the dashboard and remove containers?" "n"; then
    log "Cancelled"
    return 1
  fi
  if have docker && [[ -f docker-compose.yaml ]]; then
    docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true
    ok "Containers stopped"
  fi
  if have pgrep && pgrep -f "dashboard-web/server.mjs" >/dev/null; then
    pkill -f "dashboard-web/server.mjs" || true
    ok "Local server stopped"
  fi
  log "To remove the repo entirely: rm -rf '$SCRIPT_DIR'"
}

run_doctor() {
  cd "$SCRIPT_DIR"
  printf "${C_BOLD}Environment:${C_RESET}\n"
  printf "  OS:           %s\n" "$(uname -srm 2>/dev/null || echo unknown)"
  printf "  Node:         %s\n" "$(node -v 2>/dev/null || echo 'not installed')"
  printf "  npm:          %s\n" "$(npm -v 2>/dev/null || echo 'not installed')"
  printf "  Docker:       %s\n" "$(docker --version 2>/dev/null || echo 'not installed')"
  printf "  Compose:      %s\n" "$(docker compose version --short 2>/dev/null || docker-compose --version 2>/dev/null || echo 'not installed')"
  printf "  Git:          %s\n" "$(git --version 2>/dev/null || echo 'not installed')"
  printf "  Project root: %s\n" "$SCRIPT_DIR"
  printf "  .env:         %s\n" "$([[ -f .env ]] && echo present || echo missing)"
  printf "  cv.md:        %s\n" "$([[ -f cv.md ]] && echo present || echo missing)"
  printf "  profile.yml:  %s\n" "$([[ -f config/profile.yml ]] && echo present || echo missing)"
  printf "  Dashboard:    %s\n" "$(curl -fsS "${URL}/api/health" >/dev/null 2>&1 && echo "up at ${URL}" || echo "down")"

  if have node; then
    printf "\n${C_BOLD}Self-tests:${C_RESET}\n"
    npm test --silent 2>&1 | tail -8 || true
  fi
}

# ── Entry point ─────────────────────────────────────────────────────────────
main() {
  banner

  local mode=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --docker)    mode=docker ;;
      --local)     mode=local ;;
      --update)    mode=update ;;
      --uninstall) mode=uninstall ;;
      --doctor)    mode=doctor ;;
      -h|--help)
        sed -n '2,18p' "$0"; exit 0 ;;
      *) fail "Unknown flag: $1 (try --help)" 3 ;;
    esac
    shift
  done

  if [[ -z "$mode" ]]; then
    printf "${C_BOLD}Pick an install mode:${C_RESET}\n"
    printf "  1) Docker     ${C_DIM}— recommended; isolates Chromium + deps${C_RESET}\n"
    printf "  2) Local      ${C_DIM}— run with your system Node 20+/22${C_RESET}\n"
    printf "  3) Doctor     ${C_DIM}— diagnose environment, no install${C_RESET}\n"
    printf "  4) Cancel\n\n"
    local choice; choice=$(ask "Choice" "1")
    case "$choice" in
      1) mode=docker ;;
      2) mode=local ;;
      3) mode=doctor ;;
      *) log "Cancelled"; exit 1 ;;
    esac
  fi

  case "$mode" in
    docker)    run_docker ;;
    local)     run_local ;;
    update)    run_update ;;
    uninstall) run_uninstall ;;
    doctor)    run_doctor ;;
  esac
}

main "$@"
