/**
 * jobs.ts — evaluation job lifecycle contract.
 *
 * This models what `batch/batch-runner.sh::process_offer` does today,
 * exposed as a state machine so the popup can render a useful progress UI.
 *
 * A job moves strictly forward through a fixed set of phases. It can
 * terminate in `completed` or `failed`. Once terminal, it is immutable.
 *
 *   queued
 *     └─> extracting_jd
 *           └─> evaluating
 *                 └─> writing_report
 *                       └─> generating_pdf
 *                             └─> writing_tracker
 *                                   └─> completed
 *
 * Any phase can transition directly to `failed` with a BridgeError.
 *
 * CONTRACTS ONLY. No runtime.
 */

import type { BridgeError } from "./envelope.js";

/** Opaque job identifier. UUID v4 generated by the bridge. */
export type JobId = string & { readonly __brand: "JobId" };

export type JobPhase =
  | "queued"
  | "extracting_jd"
  | "evaluating"
  | "writing_report"
  | "generating_pdf"
  | "writing_tracker"
  | "completed"
  | "failed";

export const TERMINAL_PHASES: ReadonlySet<JobPhase> = new Set([
  "completed",
  "failed",
]);

/**
 * The input to a new evaluation job — what the extension captures from
 * the active tab and hands to the bridge. Kept deliberately small:
 *   • `url` is the canonical identifier.
 *   • `title` is a hint for display only.
 *   • `pageText` is the optional pre-extracted JD body. If provided, the
 *     bridge MAY skip Playwright JD extraction and use this directly.
 *     If omitted or below a minimum length, the bridge extracts itself.
 */
export interface EvaluationInput {
  url: string;
  title?: string;
  /** Optional pre-captured JD text. See `JD_MIN_CHARS` below. */
  pageText?: string;
  /**
   * Optional hints from the content script's heuristic detector.
   * Used for debugging and for the popup to explain "why this page".
   */
  detection?: PageDetection;
}

export const JD_MIN_CHARS = 400;

/**
 * Heuristic page-type detection output from the content script.
 * The popup shows `label` + `confidence`. The bridge ignores this except
 * for logging — the source of truth is the URL the user clicks Evaluate on.
 */
export interface PageDetection {
  label: "job_posting" | "likely_job_posting" | "not_job_posting";
  confidence: number; // 0..1
  /** Which rules matched. Free-form for now; may be tightened in Phase 4. */
  signals: readonly string[];
}

/**
 * A job snapshot as returned by GET /jobs/:id and as pushed via SSE.
 * The SSE stream emits one `JobEvent` per transition.
 */
export interface JobSnapshot {
  id: JobId;
  phase: JobPhase;
  createdAt: string;    // ISO-8601 UTC
  updatedAt: string;    // ISO-8601 UTC
  input: EvaluationInput;
  /** Populated while in-flight; may be undefined during `queued`. */
  progress?: JobProgress;
  /** Present iff phase === "completed". */
  result?: EvaluationResult;
  /** Present iff phase === "failed". */
  error?: BridgeError;
}

/**
 * Progress breadcrumbs. The bridge writes one entry per phase transition
 * so the popup can render a timeline even if it connects mid-run.
 */
export interface JobProgress {
  /** Ordered phase history, oldest first. Includes the current phase. */
  phases: readonly PhaseTransition[];
  /**
   * Reserved report number (reserved under batch/.batch-state.lock).
   * Present from `writing_report` onward. Used to build the report path.
   */
  reportNumber?: number;
}

export interface PhaseTransition {
  phase: JobPhase;
  at: string; // ISO-8601 UTC
  /** Optional one-line note the bridge can surface to the popup. */
  note?: string;
}

/**
 * Terminal result of a successful evaluation. Mirrors the fields the
 * dashboard and tracker care about, plus file paths for "Open report"
 * and "Open PDF" popup actions.
 */
export interface EvaluationResult {
  reportNumber: number;
  /** Absolute path on the host machine. */
  reportPath: string;
  /** Absolute path, or null if PDF generation was skipped/failed. */
  pdfPath: string | null;
  company: string;
  role: string;
  /** Numeric score in [0, 5]. */
  score: number;
  /** The archetype the evaluation settled on (may be "hybrid:X+Y"). */
  archetype: string;
  /** Short one-sentence TL;DR from block A of the report. */
  tldr: string;
  /**
   * What tracker row was written, exactly as it will appear in
   * data/applications.md after the next merge. The bridge computes this
   * from the TSV drop file it wrote — it does not re-parse applications.md.
   */
  trackerRow: TrackerRow;
}

/**
 * One row from data/applications.md, in the canonical 9-column shape
 * (see CLAUDE.md § TSV Format for Tracker Additions and templates/states.yml).
 */
export interface TrackerRow {
  num: number;
  date: string;         // YYYY-MM-DD
  company: string;
  role: string;
  status: TrackerStatus;
  score: `${number}/5`;
  pdf: "✅" | "❌";
  /** Markdown link, e.g. "[001](reports/001-acme-2026-04-09.md)". */
  report: string;
  notes: string;
}

/** Canonical statuses from templates/states.yml. */
export type TrackerStatus =
  | "Evaluated"
  | "Applied"
  | "Responded"
  | "Interview"
  | "Offer"
  | "Rejected"
  | "Discarded"
  | "SKIP";

/**
 * SSE stream events. The bridge emits one of these per phase transition
 * and one final `done` or `failed` event before closing the stream.
 */
export type JobEvent =
  | {
      kind: "snapshot";
      /** Full current state. Always emitted immediately on connection. */
      snapshot: JobSnapshot;
    }
  | {
      kind: "phase";
      jobId: JobId;
      phase: JobPhase;
      at: string;
      note?: string;
    }
  | {
      kind: "done";
      jobId: JobId;
      result: EvaluationResult;
    }
  | {
      kind: "failed";
      jobId: JobId;
      error: BridgeError;
    };
