/**
 * lib/network-graph.mjs — Gap-detection + outreach lever consumer for network graph.
 *
 * Reads data/network-graph.json (generated by scripts/scan-network.mjs)
 * and provides company-lookup, gap-contradiction, and leverage-path finding
 * for dashboard drawer popouts and gap chips.
 *
 * Pure deterministic — NO LLM calls, regex/keyword only.
 * In-memory cache of the JSON after first load.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GRAPH_PATH = resolve(__dirname, '..', 'data', 'network-graph.json');

let _cache = null;

// ── Media/press organizations for gap matching ────────────────────────────────

const MEDIA_ORG_SLUGS = [
  'al jazeera', 'aj+', 'aljazeera', 'huffpost', 'huffpost live', 'cnn', 'fusion',
  'abc news', 'univision', 'cctv', 'the stream', 'new day',
  'pbs', 'nbc', 'msnbc', 'bbc', 'npr', 'vice', 'buzzfeed', 'guardian',
  'new york times', 'washington post', 'politico', 'the atlantic', 'wired',
  'bloomberg', 'reuters', 'ap news', 'associated press', 'axios', 'techcrunch',
  'the verge', 'ars technica', 'fast company', 'vox', 'substack', 'media',
];

// ── Gap → relationship type mapping ──────────────────────────────────────────

const GAP_REL_MAP = [
  {
    gapPatterns: [/press[\s_-]?relation/i, /journalist[\s_-]?network/i, /media[\s_-]?contact/i, /media[\s_-]?relation/i],
    filterFn: (p) => p.press_media_potential || isMediaPerson(p),
    confidence: 'high',
    template: 'Mitchell has {count} press/media contacts from 14+ years in broadcast journalism: {names}. Networks span Al Jazeera, AJ+, HuffPost Live, CNN, Fusion, ABC News.',
  },
  {
    gapPatterns: [/broadcast[\s_-]?experience/i, /newsroom[\s_-]?experience/i, /journalism[\s_-]?background/i, /media[\s_-]?industry/i],
    filterFn: (p) => p.press_media_potential || isMediaPerson(p),
    confidence: 'high',
    template: 'Mitchell has {count} relationships from direct newsroom work at: Al Jazeera English/The Stream (founding team), HuffPost Live, Fusion/ABC News/Univision, AJ+, CNN, CCTV America. Named contacts: {names}.',
  },
  {
    gapPatterns: [/linkedin[\s_-]?network/i, /professional[\s_-]?network/i, /warm[\s_-]?intro/i, /network[\s_-]?at/i],
    filterFn: (p) => p.relationship_type.includes('linkedin_connection'),
    confidence: 'high',
    template: '{count} LinkedIn connections available as warm-intro paths. Key contacts: {names}.',
  },
  {
    gapPatterns: [/ai[\s_-]?company[\s_-]?experience/i, /developer[\s_-]?tool[\s_-]?experience/i, /startup[\s_-]?network/i],
    filterFn: (p) => {
      const co = (p.current_company || '').toLowerCase();
      return ['anthropic', 'openai', 'google', 'deepmind', 'meta', 'microsoft', 'nvidia', 'cursor', 'databricks', 'cohere', 'mistral'].some(c => co.includes(c));
    },
    confidence: 'medium',
    template: '{count} known contacts at AI/developer-tool companies: {names}. These are potential warm-intro paths.',
  },
  {
    gapPatterns: [/google[\s_-]?experience/i, /google[\s_-]?network/i, /big[\s_-]?tech[\s_-]?experience/i],
    filterFn: (p) => (p.current_company || '').toLowerCase().includes('google'),
    confidence: 'high',
    template: '{count} known Google contacts for warm-intro paths: {names}. Mitchell spent 8 years at Google.',
  },
];

function isMediaPerson(p) {
  const co = (p.current_company || '').toLowerCase();
  return MEDIA_ORG_SLUGS.some(m => co.includes(m)) ||
    p.relationship_type.some(r => ['interviewee', 'cited_in_my_work', 'cited_my_work'].includes(r));
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Load + validate ───────────────────────────────────────────────────────────

/**
 * loadNetworkGraph() → graph object or null
 * Validates schema_version. Caches in-memory.
 */
export function loadNetworkGraph() {
  if (_cache) return _cache;
  if (!existsSync(GRAPH_PATH)) return null;
  try {
    const raw = readFileSync(GRAPH_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    if (!parsed.schema_version || !Array.isArray(parsed.people)) {
      throw new Error('Invalid schema: missing schema_version or people array');
    }
    _cache = parsed;
    return _cache;
  } catch {
    return null;
  }
}

/** Invalidate the in-memory cache (useful in tests). */
export function clearCache() {
  _cache = null;
}

// ── Company lookup ────────────────────────────────────────────────────────────

/**
 * findContactsAtCompany(slug) → [{...person}]
 * Returns all known contacts whose current_company matches the slug.
 * Applies overrides.json corrections.
 */
export function findContactsAtCompany(slug) {
  const graph = loadNetworkGraph();
  if (!graph) return [];
  const needle = slug.toLowerCase();
  return graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );
}

/**
 * findContactsInIndustry(industry) → [{...person}]
 * Returns all contacts with press_media_potential=true, or whose company
 * matches an industry keyword.
 */
export function findContactsInIndustry(industry) {
  const graph = loadNetworkGraph();
  if (!graph) return [];
  const needle = industry.toLowerCase();

  if (/press|journal|media|broadcast|news/i.test(needle)) {
    return graph.people.filter(p => p.press_media_potential || isMediaPerson(p));
  }

  if (/ai|machine.learning|llm|tech|software|developer/i.test(needle)) {
    return graph.people.filter(p => {
      const co = (p.current_company || '').toLowerCase();
      return ['ai', 'anthropic', 'openai', 'google', 'meta', 'microsoft', 'nvidia', 'databricks', 'cursor', 'cohere'].some(k => co.includes(k));
    });
  }

  // Generic: match company against industry keyword
  return graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );
}

// ── Leverage path discovery ───────────────────────────────────────────────────

/**
 * findLeveragePathTo(target_company, role?) → { direct, one_hop, no_path }
 *
 * direct  = people Mitchell knows directly at that company
 * one_hop = people who know people at that company (based on shared org context)
 *           In v1 this is approximated by former colleagues now at target company
 * no_path = boolean — true only when both direct and one_hop are empty
 */
export function findLeveragePathTo(target_company, role = '') {
  const graph = loadNetworkGraph();
  if (!graph) return { direct: [], one_hop: [], no_path: true };

  const needle = target_company.toLowerCase();

  // Direct: connections currently at target company
  const direct = graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );

  // One-hop: people with evidence_sources mentioning the target company,
  // or former colleagues (Google, media) who may now be at target company
  const oneHopIds = new Set(direct.map(p => p.id));
  const one_hop = graph.people.filter(p => {
    if (oneHopIds.has(p.id)) return false;
    return p.evidence_sources.some(e => e.context.toLowerCase().includes(needle));
  });

  return {
    direct,
    one_hop,
    no_path: direct.length === 0 && one_hop.length === 0,
  };
}

// ── Gap checking ──────────────────────────────────────────────────────────────

/**
 * checkGap(gapKey, role?) → { contradicts, evidence_summary, draft_response, contacts_to_tap }
 *
 * @param {string} gapKey  — text of the gap claim
 * @param {object} [role]  — optional role context
 */
export function checkGap(gapKey, role = {}) {
  const graph = loadNetworkGraph();
  if (!graph) {
    return {
      contradicts: false,
      evidence_summary: 'Network graph not yet generated. Run: node scripts/scan-network.mjs',
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  let matchedRule = null;
  for (const rule of GAP_REL_MAP) {
    if (rule.gapPatterns.some(re => re.test(gapKey))) {
      matchedRule = rule;
      break;
    }
  }

  if (!matchedRule) {
    return {
      contradicts: false,
      evidence_summary: `No network rule matched for gap: "${gapKey}"`,
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  const matching = graph.people.filter(matchedRule.filterFn);
  if (matching.length === 0) {
    return {
      contradicts: false,
      evidence_summary: `No contacts found matching gap rule for: "${gapKey}"`,
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  const names = matching.slice(0, 5).map(p => p.name).join(', ');
  const draftResponse = matchedRule.template
    .replace('{count}', String(matching.length))
    .replace('{names}', names);

  return {
    contradicts: true,
    evidence_summary: `${matching.length} contacts contradict this gap: ${names}`,
    draft_response: draftResponse,
    contacts_to_tap: matching.slice(0, 10),
    confidence: matchedRule.confidence,
  };
}

// ── Render ────────────────────────────────────────────────────────────────────

/**
 * renderNetworkCard(contacts, opts) → HTML string
 * For drawer popouts showing known contacts at a target company.
 */
export function renderNetworkCard(contacts = [], opts = {}) {
  if (!Array.isArray(contacts) || contacts.length === 0) return '';

  const label = opts.label || 'Network connections';
  const rows = contacts.slice(0, 10).map(p => {
    const co = p.current_company ? ` · ${escHtml(p.current_company)}` : '';
    const role = p.current_role ? ` (${escHtml(p.current_role)})` : '';
    const rels = p.relationship_type.join(', ');
    return `<li class="network-card__contact" data-tap="${escHtml(p.tap_potential)}">
      <span class="network-card__name">${escHtml(p.name)}</span>${role}${co}
      <span class="network-card__rel" aria-label="relationship">${escHtml(rels)}</span>
    </li>`;
  }).join('');

  const moreCount = Math.max(0, contacts.length - 10);
  const moreLabel = moreCount > 0 ? `<p class="network-card__more">+${moreCount} more</p>` : '';

  return `<div class="network-card" role="complementary" aria-label="${escHtml(label)}">
  <div class="network-card__header">
    <span class="network-card__icon" aria-hidden="true">🔗</span>
    <span class="network-card__label">${escHtml(label)} (${contacts.length})</span>
  </div>
  <ul class="network-card__list">${rows}</ul>
  ${moreLabel}
</div>`;
}

// ── Summary accessor ──────────────────────────────────────────────────────────

/**
 * getNetworkSummary() → { total, media_contacts, by_relationship, in_target_companies }
 */
export function getNetworkSummary() {
  const graph = loadNetworkGraph();
  if (!graph) return null;
  return graph.summary;
}
