/**
 * lib/network-graph.mjs — Gap-detection + outreach lever consumer for network graph.
 *
 * Reads data/network-graph.json (generated by scripts/scan-network.mjs)
 * and provides company-lookup, gap-contradiction, and leverage-path finding
 * for dashboard drawer popouts and gap chips.
 *
 * Pure deterministic — NO LLM calls, regex/keyword only.
 * In-memory cache of the JSON after first load.
 */

import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GRAPH_PATH = resolve(__dirname, '..', 'data', 'network-graph.json');
// ζ ZETA Run-Batch addition 2026-05-19: fall-back source. The legacy
// `data/network-graph.json` (generated by scripts/scan-network.mjs) is
// NOT currently present on the production checkout — every call to
// findContactsAtCompany() / findLeveragePathTo() / checkGap() was
// silently returning empty because the file isn't there. The fresh
// `data/network-database.json` (built by overnight ζ.1 work, 2,824
// people with target-company resolution and warm_to_target_companies
// arrays) is on disk and DOES have the data. This module now reads
// from network-database.json shape-converted to the older schema
// when network-graph.json is absent, so existing callers (drawer card
// at scripts/build-dashboard.mjs:3079, gap chips, alignment scorer)
// get real signal instead of silently-empty arrays.
const DB_PATH = resolve(__dirname, '..', 'data', 'network-database.json');

// γ GAMMA fix 2026-05-19 (audit HIGH-3): cache used to be `let _cache = null`
// with no TTL — long-running dashboard-server processes pinned the in-memory
// graph to whichever file existed at first read. Now we track the file's
// mtime alongside the parsed body and re-read whenever the file changes.
let _cache = null;
let _cacheMtimeMs = 0;
let _cacheSource = null; // 'graph' | 'database' — tracks which file populated the cache

// ── Media/press organizations for gap matching ────────────────────────────────

const MEDIA_ORG_SLUGS = [
  'al jazeera', 'aj+', 'aljazeera', 'huffpost', 'huffpost live', 'cnn', 'fusion',
  'abc news', 'univision', 'cctv', 'the stream', 'new day',
  'pbs', 'nbc', 'msnbc', 'bbc', 'npr', 'vice', 'buzzfeed', 'guardian',
  'new york times', 'washington post', 'politico', 'the atlantic', 'wired',
  'bloomberg', 'reuters', 'ap news', 'associated press', 'axios', 'techcrunch',
  'the verge', 'ars technica', 'fast company', 'vox', 'substack', 'media',
];

// ── Gap → relationship type mapping ──────────────────────────────────────────

const GAP_REL_MAP = [
  {
    gapPatterns: [/press[\s_-]?relation/i, /journalist[\s_-]?network/i, /media[\s_-]?contact/i, /media[\s_-]?relation/i],
    filterFn: (p) => p.press_media_potential || isMediaPerson(p),
    confidence: 'high',
    template: 'Mitchell has {count} press/media contacts from 14+ years in broadcast journalism: {names}. Networks span Al Jazeera, AJ+, HuffPost Live, CNN, Fusion, ABC News.',
  },
  {
    gapPatterns: [/broadcast[\s_-]?experience/i, /newsroom[\s_-]?experience/i, /journalism[\s_-]?background/i, /media[\s_-]?industry/i],
    filterFn: (p) => p.press_media_potential || isMediaPerson(p),
    confidence: 'high',
    template: 'Mitchell has {count} relationships from direct newsroom work at: Al Jazeera English/The Stream (founding team), HuffPost Live, Fusion/ABC News/Univision, AJ+, CNN, CCTV America. Named contacts: {names}.',
  },
  {
    gapPatterns: [/linkedin[\s_-]?network/i, /professional[\s_-]?network/i, /warm[\s_-]?intro/i, /network[\s_-]?at/i],
    filterFn: (p) => p.relationship_type.includes('linkedin_connection'),
    confidence: 'high',
    template: '{count} LinkedIn connections available as warm-intro paths. Key contacts: {names}.',
  },
  {
    gapPatterns: [/ai[\s_-]?company[\s_-]?experience/i, /developer[\s_-]?tool[\s_-]?experience/i, /startup[\s_-]?network/i],
    filterFn: (p) => {
      const co = (p.current_company || '').toLowerCase();
      return ['anthropic', 'openai', 'google', 'deepmind', 'meta', 'microsoft', 'nvidia', 'cursor', 'databricks', 'cohere', 'mistral'].some(c => co.includes(c));
    },
    confidence: 'medium',
    template: '{count} known contacts at AI/developer-tool companies: {names}. These are potential warm-intro paths.',
  },
  {
    gapPatterns: [/google[\s_-]?experience/i, /google[\s_-]?network/i, /big[\s_-]?tech[\s_-]?experience/i],
    filterFn: (p) => (p.current_company || '').toLowerCase().includes('google'),
    confidence: 'high',
    template: '{count} known Google contacts for warm-intro paths: {names}. Mitchell spent 8 years at Google.',
  },
];

function isMediaPerson(p) {
  const co = (p.current_company || '').toLowerCase();
  return MEDIA_ORG_SLUGS.some(m => co.includes(m)) ||
    p.relationship_type.some(r => ['interviewee', 'cited_in_my_work', 'cited_my_work'].includes(r));
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Load + validate ───────────────────────────────────────────────────────────

/**
 * loadNetworkGraph() → graph object or null
 * Validates schema_version. Caches in-memory.
 *
 * ζ ZETA Run-Batch 2026-05-19 — primary source is `data/network-graph.json`
 * (legacy, from scan-network.mjs). When that file is absent we fall back
 * to `data/network-database.json` (fresh ζ.1 source), shape-converted
 * to the older `people[]` schema so existing callers don't change.
 *
 * The shape conversion is intentionally minimal — only the fields the
 * existing consumers (findContactsAtCompany, findLeveragePathTo,
 * checkGap, renderNetworkCard) read off `people[i]`: id, name,
 * current_company, current_role, relationship_type, evidence_sources,
 * tap_potential, press_media_potential. Connection-warmth metadata
 * (connected_on, last_engaged_at) is preserved as `_freshness_meta`
 * so the honest-warmth gate can pick it up without re-reading the DB.
 */
export function loadNetworkGraph() {
  // Primary path: legacy network-graph.json (if it exists)
  if (existsSync(GRAPH_PATH)) {
    let mtimeMs = 0;
    try { mtimeMs = statSync(GRAPH_PATH).mtimeMs; } catch { /* ignore */ }
    if (_cache && _cacheSource === 'graph' && mtimeMs === _cacheMtimeMs) return _cache;
    try {
      const raw = readFileSync(GRAPH_PATH, 'utf8');
      const parsed = JSON.parse(raw);
      if (!parsed.schema_version || !Array.isArray(parsed.people)) {
        throw new Error('Invalid schema: missing schema_version or people array');
      }
      parsed._loaded_at = new Date().toISOString();
      parsed._source_mtime = new Date(mtimeMs).toISOString();
      parsed._source_file = 'network-graph.json';
      _cache = parsed;
      _cacheMtimeMs = mtimeMs;
      _cacheSource = 'graph';
      return _cache;
    } catch {
      // fall through to DB fallback
    }
  }

  // Fallback: network-database.json (fresh ζ.1 source)
  if (!existsSync(DB_PATH)) {
    _cache = null;
    _cacheMtimeMs = 0;
    _cacheSource = null;
    return null;
  }
  let dbMtimeMs = 0;
  try { dbMtimeMs = statSync(DB_PATH).mtimeMs; } catch { /* ignore */ }
  if (_cache && _cacheSource === 'database' && dbMtimeMs === _cacheMtimeMs) return _cache;
  try {
    const raw = readFileSync(DB_PATH, 'utf8');
    const db = JSON.parse(raw);
    if (!db.schema_version || !Array.isArray(db.people)) {
      throw new Error('Invalid network-database.json schema');
    }
    // Convert network-database people[] shape → network-graph people[] shape.
    // Only the fields existing consumers read.
    const people = db.people.map(p => {
      const isFirstDegree = p.degree === 1 || p.degree === '1';
      const relationshipType = [];
      if (isFirstDegree) relationshipType.push('linkedin_connection');
      // 2nd-degree people who are warm paths get tagged so existing
      // gap-rules that look for `linkedin_connection` keep firing for the
      // 1st-degree segment but don't over-claim 2nd-degree as direct.
      const warmTargets = Array.isArray(p.warm_to_target_companies) ? p.warm_to_target_companies : [];
      return {
        id: p.id,
        name: p.full_name || `${p.first || ''} ${p.last || ''}`.trim(),
        current_company: p.current_company || '',
        current_role: p.current_role || '',
        relationship_type: relationshipType,
        evidence_sources: [], // network-database.json doesn't carry the legacy evidence_sources schema
        tap_potential: warmTargets.length ? 'high' : (isFirstDegree ? 'medium' : 'low'),
        press_media_potential: false,
        // ζ Run-Batch addition: freshness metadata for honest-warmth gating
        _freshness_meta: {
          connected_on: p.connected_on || null,
          degree: p.degree || null,
          linkedin_last_engaged_at: p.engagement?.linkedin_last_engaged_at || null,
          linkedin_posts_engaged_count: p.engagement?.linkedin_posts_engaged_count || 0,
          warm_to_target_companies: warmTargets,
        },
      };
    });
    const synth = {
      schema_version: 1,
      people,
      summary: {
        total: db.total || people.length,
        media_contacts: 0,
        by_relationship: { linkedin_connection: people.filter(x => x.relationship_type.includes('linkedin_connection')).length },
        in_target_companies: db.totals_by_target || {},
      },
      _loaded_at: new Date().toISOString(),
      _source_mtime: new Date(dbMtimeMs).toISOString(),
      _source_file: 'network-database.json',
      _db_last_run: db.last_run || null,
    };
    _cache = synth;
    _cacheMtimeMs = dbMtimeMs;
    _cacheSource = 'database';
    return _cache;
  } catch (err) {
    return null;
  }
}

/** Invalidate the in-memory cache (useful in tests). */
export function clearCache() {
  _cache = null;
  _cacheMtimeMs = 0;
  _cacheSource = null;
}

/**
 * γ GAMMA addition 2026-05-19 — expose the cache's freshness so the dashboard
 * can render a "graph last refreshed" chip on warm-path surfaces.
 *
 * ζ ZETA Run-Batch 2026-05-19 — extended to surface the actual source
 * (network-graph.json vs network-database.json fallback) so the chip
 * doesn't lie about "graph: not built" when the DB is on disk and live.
 */
export function getNetworkGraphFreshness() {
  // Prefer the legacy source if present; report it.
  if (existsSync(GRAPH_PATH)) {
    let mtimeMs = 0;
    try { mtimeMs = statSync(GRAPH_PATH).mtimeMs; } catch { /* ignore */ }
    const ageMs = Date.now() - mtimeMs;
    return {
      available: true,
      source_file: 'network-graph.json',
      source_mtime_iso: new Date(mtimeMs).toISOString(),
      age_days: Math.round(ageMs / 86_400_000),
      age_hours: Math.round(ageMs / 3_600_000),
      cached_in_process: _cache !== null,
      process_cache_mtime_iso: _cacheMtimeMs ? new Date(_cacheMtimeMs).toISOString() : null,
    };
  }
  // Fallback: report network-database.json freshness so the chip is honest
  if (existsSync(DB_PATH)) {
    let mtimeMs = 0;
    try { mtimeMs = statSync(DB_PATH).mtimeMs; } catch { /* ignore */ }
    const ageMs = Date.now() - mtimeMs;
    return {
      available: true,
      source_file: 'network-database.json',
      source_mtime_iso: new Date(mtimeMs).toISOString(),
      age_days: Math.round(ageMs / 86_400_000),
      age_hours: Math.round(ageMs / 3_600_000),
      cached_in_process: _cache !== null,
      process_cache_mtime_iso: _cacheMtimeMs ? new Date(_cacheMtimeMs).toISOString() : null,
      note: 'falling back to network-database.json — run scripts/scan-network.mjs to regenerate the legacy graph.json if needed',
    };
  }
  return { available: false, reason: 'neither network-graph.json nor network-database.json present' };
}

// ── Company lookup ────────────────────────────────────────────────────────────

/**
 * findContactsAtCompany(slug) → [{...person}]
 * Returns all known contacts whose current_company matches the slug.
 * Applies overrides.json corrections.
 *
 * ζ ZETA Run-Batch 2026-05-19 — when the data source is the new
 * network-database.json fallback, this also considers people who are
 * warm to the target via `warm_to_target_companies` (the canonical
 * "this connection of mine can intro me to X" signal). This is gated
 * by a freshness check on `connected_on` (an 18-month staleness
 * threshold) so we don't claim a 2-year-old connection is a warm intro.
 *
 * Returns first-degree matches FIRST (substring on current_company),
 * then warm-path matches (2nd-degree intros via the new DB), each
 * annotated with `_warm_via_target_slug` so the renderer can label.
 */
export function findContactsAtCompany(slug) {
  const graph = loadNetworkGraph();
  if (!graph) return [];
  const needle = slug.toLowerCase();
  const firstDegree = graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );
  // If we're on the new DB, also surface people whose warm_to_target_companies
  // arrays point at this slug — these are connections of Mitchell's who can
  // intro him into the target. Honest-warmth: only include where the
  // connection is recent enough (connected_on within 18 months) to be
  // plausibly warm. Stale connections get an honest `_stale_warmth: true` flag.
  if (graph._source_file === 'network-database.json') {
    const matchingSlug = needle.replace(/[^a-z0-9]+/g, '');
    const eighteenMonthsAgo = Date.now() - (18 * 30 * 86_400_000);
    for (const p of graph.people) {
      if (firstDegree.includes(p)) continue;
      const warm = p._freshness_meta?.warm_to_target_companies || [];
      if (!warm.length) continue;
      const hit = warm.find(w => {
        const wSlug = String(w.company_slug || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
        return wSlug && (wSlug === matchingSlug || wSlug.includes(matchingSlug) || matchingSlug.includes(wSlug));
      });
      if (!hit) continue;
      const connectedOn = p._freshness_meta?.connected_on;
      let stale = false;
      if (connectedOn) {
        try {
          const ts = new Date(connectedOn).getTime();
          if (Number.isFinite(ts) && ts < eighteenMonthsAgo) stale = true;
        } catch { /* unparseable date — leave stale=false; honest disclosure happens elsewhere */ }
      }
      firstDegree.push({
        ...p,
        _warm_via_target_slug: hit.company_slug,
        _warm_via_target_name: hit.target_name,
        _stale_warmth: stale,
      });
    }
  }
  return firstDegree;
}

/**
 * findContactsInIndustry(industry) → [{...person}]
 * Returns all contacts with press_media_potential=true, or whose company
 * matches an industry keyword.
 */
export function findContactsInIndustry(industry) {
  const graph = loadNetworkGraph();
  if (!graph) return [];
  const needle = industry.toLowerCase();

  if (/press|journal|media|broadcast|news/i.test(needle)) {
    return graph.people.filter(p => p.press_media_potential || isMediaPerson(p));
  }

  if (/ai|machine.learning|llm|tech|software|developer/i.test(needle)) {
    return graph.people.filter(p => {
      const co = (p.current_company || '').toLowerCase();
      return ['ai', 'anthropic', 'openai', 'google', 'meta', 'microsoft', 'nvidia', 'databricks', 'cursor', 'cohere'].some(k => co.includes(k));
    });
  }

  // Generic: match company against industry keyword
  return graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );
}

// ── Leverage path discovery ───────────────────────────────────────────────────

/**
 * findLeveragePathTo(target_company, role?) → { direct, one_hop, no_path }
 *
 * direct  = people Mitchell knows directly at that company
 * one_hop = people who know people at that company (based on shared org context)
 *           In v1 this is approximated by former colleagues now at target company
 * no_path = boolean — true only when both direct and one_hop are empty
 */
export function findLeveragePathTo(target_company, role = '') {
  const graph = loadNetworkGraph();
  if (!graph) return { direct: [], one_hop: [], no_path: true };

  const needle = target_company.toLowerCase();

  // Direct: connections currently at target company
  const direct = graph.people.filter(p =>
    (p.current_company || '').toLowerCase().includes(needle)
  );

  // One-hop: people with evidence_sources mentioning the target company,
  // or former colleagues (Google, media) who may now be at target company
  const oneHopIds = new Set(direct.map(p => p.id));
  const one_hop = graph.people.filter(p => {
    if (oneHopIds.has(p.id)) return false;
    return p.evidence_sources.some(e => e.context.toLowerCase().includes(needle));
  });

  return {
    direct,
    one_hop,
    no_path: direct.length === 0 && one_hop.length === 0,
  };
}

// ── Gap checking ──────────────────────────────────────────────────────────────

/**
 * checkGap(gapKey, role?) → { contradicts, evidence_summary, draft_response, contacts_to_tap }
 *
 * @param {string} gapKey  — text of the gap claim
 * @param {object} [role]  — optional role context
 */
export function checkGap(gapKey, role = {}) {
  const graph = loadNetworkGraph();
  if (!graph) {
    return {
      contradicts: false,
      evidence_summary: 'Network graph not yet generated. Run: node scripts/scan-network.mjs',
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  let matchedRule = null;
  for (const rule of GAP_REL_MAP) {
    if (rule.gapPatterns.some(re => re.test(gapKey))) {
      matchedRule = rule;
      break;
    }
  }

  if (!matchedRule) {
    return {
      contradicts: false,
      evidence_summary: `No network rule matched for gap: "${gapKey}"`,
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  const matching = graph.people.filter(matchedRule.filterFn);
  if (matching.length === 0) {
    return {
      contradicts: false,
      evidence_summary: `No contacts found matching gap rule for: "${gapKey}"`,
      draft_response: '',
      contacts_to_tap: [],
    };
  }

  const names = matching.slice(0, 5).map(p => p.name).join(', ');
  const draftResponse = matchedRule.template
    .replace('{count}', String(matching.length))
    .replace('{names}', names);

  return {
    contradicts: true,
    evidence_summary: `${matching.length} contacts contradict this gap: ${names}`,
    draft_response: draftResponse,
    contacts_to_tap: matching.slice(0, 10),
    confidence: matchedRule.confidence,
  };
}

// ── Render ────────────────────────────────────────────────────────────────────

/**
 * renderNetworkCard(contacts, opts) → HTML string
 * For drawer popouts showing known contacts at a target company.
 *
 * ζ ZETA Run-Batch 2026-05-19 — render-side privacy + honesty pass:
 *   • Stale warmth (connected >18mo ago, no recent engagement) gets a
 *     visible "stale" dimmer + tooltip so the badge doesn't lie.
 *   • Warm-via-mutual paths from the new DB get a "→ via {name}" tag
 *     so the reader knows it's a 2nd-degree path, not a 1st-degree contact.
 *   • Email addresses, phone numbers, and other PII are NEVER rendered
 *     here — this card is for "I know N people" signal density only;
 *     the popout / drawer's Network Database tab is the surface that
 *     reveals contact details, gated by Cloudflare Access auth.
 */
export function renderNetworkCard(contacts = [], opts = {}) {
  if (!Array.isArray(contacts) || contacts.length === 0) return '';

  const label = opts.label || 'Network connections';
  const freshCount = contacts.filter(c => !c._stale_warmth).length;
  const staleCount = contacts.length - freshCount;
  const rows = contacts.slice(0, 10).map(p => {
    const co = p.current_company ? ` · ${escHtml(p.current_company)}` : '';
    const role = p.current_role ? ` (${escHtml(p.current_role)})` : '';
    const rels = (p.relationship_type || []).join(', ');
    // ζ run-batch addition — surface the warm-via path so a 2nd-degree
    // intro doesn't masquerade as a direct contact.
    const warmVia = p._warm_via_target_name
      ? ` <span class="network-card__via" style="color:var(--text-4);font-size:11px">→ via ${escHtml(p._warm_via_target_name)}</span>`
      : '';
    const staleAttr = p._stale_warmth
      ? ' data-stale="true" style="opacity:0.55" title="connection is >18mo old with no recent engagement — verify before treating as warm"'
      : '';
    return `<li class="network-card__contact" data-tap="${escHtml(p.tap_potential)}"${staleAttr}>
      <span class="network-card__name">${escHtml(p.name)}</span>${role}${co}${warmVia}
      <span class="network-card__rel" aria-label="relationship">${escHtml(rels)}</span>
    </li>`;
  }).join('');

  const moreCount = Math.max(0, contacts.length - 10);
  const moreLabel = moreCount > 0 ? `<p class="network-card__more">+${moreCount} more</p>` : '';
  // Honest-warmth disclosure: when stale count is non-zero, surface a
  // small caveat so a "23 contacts" badge doesn't oversell.
  const honestDisclosure = staleCount > 0
    ? `<p class="network-card__more" style="color:var(--text-4);font-size:11px">${freshCount} fresh · ${staleCount} stale (>18mo, no recent engagement)</p>`
    : '';

  return `<div class="network-card" role="complementary" aria-label="${escHtml(label)}">
  <div class="network-card__header">
    <span class="network-card__icon" aria-hidden="true">🔗</span>
    <span class="network-card__label">${escHtml(label)} (${contacts.length})</span>
  </div>
  <ul class="network-card__list">${rows}</ul>
  ${moreLabel}
  ${honestDisclosure}
</div>`;
}

// ── Summary accessor ──────────────────────────────────────────────────────────

/**
 * getNetworkSummary() → { total, media_contacts, by_relationship, in_target_companies }
 */
export function getNetworkSummary() {
  const graph = loadNetworkGraph();
  if (!graph) return null;
  return graph.summary;
}
