// Auto-generated by prebuild.mjs — do not edit manually
import type { CandidateProfile } from '../types/profile';

export const seedProfile: CandidateProfile = {
  "identity": {
    "name": "Benson Chiang",
    "email": "benson0605@gmail.com",
    "phone": "",
    "location": "Taipei, Taiwan",
    "timezone": "GMT+8",
    "languages": [
      "English (native)",
      "Mandarin (native)"
    ],
    "linkedin": "linkedin.com/in/benson-chiang",
    "portfolio": "https://substack.com/@bensonchiang",
    "github": "https://github.com/BensonChiang0605"
  },
  "targeting": {
    "primaryRoles": [
      "Growth Marketing Manager",
      "Product Manager",
      "Growth Associate"
    ],
    "archetypes": [
      {
        "name": "Growth Marketing",
        "level": "Junior/Mid",
        "fit": "primary"
      },
      {
        "name": "Product Manager",
        "level": "Associate/Mid",
        "fit": "primary"
      },
      {
        "name": "Growth Product Manager",
        "level": "Associate/Mid",
        "fit": "primary"
      },
      {
        "name": "BDR / Sales",
        "level": "Mid",
        "fit": "secondary"
      },
      {
        "name": "Fintech Growth/Product",
        "level": "Junior/Mid",
        "fit": "secondary"
      }
    ],
    "industries": []
  },
  "narrative": {
    "headline": "Growth-oriented founder with finance background and full-funnel ownership",
    "exitStory": "Left institutional finance to build my own product. Grew Renmory to 1,000+ users in 4 months running the full growth stack solo. Now looking for a growth or product role where I can apply founder-level experimentation skills at real scale, with a team and proper infrastructure.",
    "superpowers": [
      "Full-funnel growth ownership (acquisition through retention, solo, with real money)",
      "Finance + growth combination (regulated environment + scrappy builder)",
      "Bilingual English/Mandarin (native in both, operates across AU/TW/SG/HK)",
      "Technical fluency (Python, JS, SQL — more technical than typical growth hire)",
      "SEO/AEO strategy that got cited in Google AI Summary"
    ],
    "proofPoints": [
      {
        "name": "Renmory",
        "heroMetric": "1,000+ users in 4 months, doubled conversion rate 4%→8%"
      },
      {
        "name": "Mercer Automation",
        "heroMetric": "70% reduction in manual effort, 15+ hrs/month saved"
      },
      {
        "name": "Grey Rhino",
        "heroMetric": "AI-powered SaaS MVP for Taiwanese education market"
      }
    ]
  },
  "compensation": {
    "targetRange": "A$90K-110K",
    "currency": "AUD",
    "minimum": "A$90K for Australia; NT$100,000/month for Taiwan",
    "locationFlexibility": "Remote, Taiwan, or Melbourne are all acceptable. Currently in Taiwan and indifferent/comfortable about relocating to Melbourne for the right AU role."
  },
  "location": {
    "country": "Taiwan",
    "city": "Taipei",
    "timezone": "GMT+8",
    "visaStatus": "NZ/TW dual citizen. Full work rights in AU, NZ, Taiwan.",
    "onsiteAvailability": "Can relocate to Melbourne and is indifferent/comfortable about doing so. Open to hybrid if in AU."
  },
  "strengths": {
    "skills": {
      "Growth & Marketing": [
        "Lead Generation",
        "Cold Outreach",
        "SEO",
        "AEO",
        "Answer Engine Optimisation",
        "SEO Content Strategy",
        "Long-Tail Keyword Research",
        "Meta Ads",
        "Community Marketing",
        "Content Strategy"
      ],
      "Analytics & Data": [
        "Google Analytics",
        "Google Search Console",
        "Funnel Analysis",
        "A/B Testing",
        "Cohort Analysis",
        "Custom Dashboards",
        "Advanced Excel"
      ],
      "Product & Design": [
        "Rapid Prototyping",
        "UI/UX Design",
        "Market Validation",
        "Information Architecture",
        "User Research"
      ],
      "Technical": [
        "Python",
        "JavaScript",
        "SQL",
        "React",
        "Flask",
        "React Native/Expo",
        "AI-Powered Content Pipelines"
      ],
      "Tools": [
        "Claude Code",
        "Codex",
        "Meta Ads Manager",
        "Google Analytics",
        "Figma"
      ],
      "Languages": [
        "English (native)",
        "Mandarin (native)"
      ]
    },
    "keyStrengths": []
  },
  "dealBreakers": [],
  "cv": {
    "summary": "Growth-oriented generalist with experience across product building, funnel optimisation, and data-driven experimentation. Scaled a consumer product to 1,000+ users by analysing onboarding funnels, running A/B tests, and doubling conversion rates. Backed by institutional finance experience delivering reporting and automation in a regulated environment. ---",
    "experience": [
      {
        "title": "Founder",
        "company": "Renmory (Kahoot for Weddings)",
        "dates": "Dec 2025 – Present",
        "bullets": [
          "Built a wedding trivia platform enabling users to create personalised wedding games in seconds. Scaled to 1,000+ users globally within 4 months of launch.",
          "Identified onboarding drop-off points through Google Analytics funnel analysis and iterated on the user journey, doubling conversion rates from 4% to 8%.",
          "Lowered rolling average time-to-purchase from 17 days to 7 by experimenting with pricing models, shifting from upfront payment to flexible timing with an early-bird offer.",
          "Devised and executed an SEO/AEO campaign that made organic search Renmory's second-largest inbound lead channel at 30% and led to citation in Google AI Summary.",
          "Grew organic reach to 1.8M impressions in month one via a community-first content strategy across Threads, Instagram, Rednote, and TikTok, bridging content discovery with product activation.",
          "Built an AI-powered content engine that automatically transforms high-performing social posts into polished blog posts and Instagram carousels, scaling content production without scaling headcount.",
          "Designed and launched a B2B affiliate program targeting wedding consultants in Taiwan, including promo codes, commission structure, and partner-facing collateral.",
          "Expanded from Taiwan into Singapore and Hong Kong, adapting product copy, onboarding flows, and marketing materials for each market."
        ]
      },
      {
        "title": "Investment Consulting Analyst",
        "company": "Mercer Investments",
        "dates": "Jan 2024 – Aug 2025",
        "bullets": [
          "Identified inefficiencies in quarterly reporting and trade execution workflows, building Python automations that reduced manual effort by 70% and saved 15+ hours monthly.",
          "Designed and proposed a streamlined reporting workflow in coordination with the India operations team, reducing monthly client reporting turnaround from 2 weeks to 2 business days.",
          "Translated complex investment data into clear, actionable narratives for institutional stakeholders, distilling performance trends and strategic recommendations into quarterly reporting presentations.",
          "Documented every automation with input/output specifications, user guides, test results, and requirement specs, enabling compliance team handoff and long-term maintainability."
        ]
      },
      {
        "title": "Co-Founder",
        "company": "Grey Rhino",
        "dates": "Nov 2023 – Nov 2024",
        "bullets": [
          "Designed and launched an AI-powered SaaS MVP (Flask, React, SQL) for the Taiwanese education market, managing the full product lifecycle from user research through to delivery."
        ]
      },
      {
        "title": "Co-Founder",
        "company": "Sweetee",
        "dates": "",
        "bullets": [
          "Co-founded a couples relationship app, designing quiz card UI components, colour systems by category, and handoff specifications for React Native/Expo development."
        ]
      }
    ],
    "education": [
      "Bachelor of Commerce (Finance), University of Melbourne (2020–2022)"
    ],
    "skills": {
      "Growth & Marketing": [
        "Lead Generation",
        "Cold Outreach",
        "SEO",
        "AEO",
        "Answer Engine Optimisation",
        "SEO Content Strategy",
        "Long-Tail Keyword Research",
        "Meta Ads",
        "Community Marketing",
        "Content Strategy"
      ],
      "Analytics & Data": [
        "Google Analytics",
        "Google Search Console",
        "Funnel Analysis",
        "A/B Testing",
        "Cohort Analysis",
        "Custom Dashboards",
        "Advanced Excel"
      ],
      "Product & Design": [
        "Rapid Prototyping",
        "UI/UX Design",
        "Market Validation",
        "Information Architecture",
        "User Research"
      ],
      "Technical": [
        "Python",
        "JavaScript",
        "SQL",
        "React",
        "Flask",
        "React Native/Expo",
        "AI-Powered Content Pipelines"
      ],
      "Tools": [
        "Claude Code",
        "Codex",
        "Meta Ads Manager",
        "Google Analytics",
        "Figma"
      ],
      "Languages": [
        "English (native)",
        "Mandarin (native)"
      ]
    }
  },
  "searchSources": {
    "totalCompanies": 111,
    "enabledCompanies": 96,
    "positiveKeywords": [
      "Growth",
      "Growth Marketing",
      "Growth Manager",
      "Demand Gen",
      "Lifecycle Marketing",
      "Performance Marketing",
      "Digital Marketing",
      "Marketing Manager",
      "Content Marketing",
      "SEO",
      "Product Manager",
      "Product Marketing",
      "Product Ops",
      "Product Strategy",
      "Technical PM",
      "BDR",
      "Business Development",
      "Account Executive",
      "Partnerships",
      "Sales Development",
      "Fintech",
      "GTM",
      "RevOps",
      "Community Manager",
      "Acquisition"
    ],
    "negativeKeywords": [
      "Intern",
      ".NET",
      "Java ",
      "iOS",
      "Android",
      "PHP",
      "Ruby",
      "Embedded",
      "Firmware",
      "FPGA",
      "ASIC",
      "Blockchain",
      "Web3",
      "Crypto",
      "AI Engineer",
      "Machine Learning Engineer",
      "ML Engineer",
      "Software Engineer",
      "Backend",
      "Frontend",
      "Full Stack",
      "Solutions Architect",
      "Solution Architect",
      "Solutions Engineer",
      "Developer Advocate",
      "DevRel",
      "Forward Deployed",
      "FDE",
      "Salesforce Admin",
      "SAP ",
      "Oracle EBS",
      "Mainframe",
      "COBOL",
      "Director",
      "VP ",
      "Principal",
      "Staff"
    ],
    "companyNames": [
      "Anthropic",
      "OpenAI",
      "PolyAI",
      "Parloa",
      "Intercom",
      "Hume AI",
      "ElevenLabs",
      "Deepgram",
      "Vapi",
      "Bland AI",
      "Retool",
      "Airtable",
      "Vercel",
      "Temporal",
      "Arize AI",
      "RunPod",
      "Weights & Biases (CoreWeave)",
      "Glean",
      "Ada",
      "LivePerson"
    ]
  },
  "proofPoints": [
    {
      "section": "Renmory — Growth Metrics",
      "bullets": [
        "Grew to 1,000+ users globally within 4 months of launch",
        "35+ paying customers in first month with zero paid acquisition",
        "Doubled conversion rate from 4% to 8% through funnel analysis and onboarding iteration",
        "Lowered rolling average time-to-purchase from 17 days to 7 by experimenting with pricing models (shifted from upfront payment to flexible timing + early bird offer)",
        "Built 3 lead magnets (question bank preview, seat organiser tool, wedding checklist); seat organiser alone attracted 10% of total leads in its first month",
        "Made organic search Renmory's second-largest inbound lead channel at 30% through SEO and AEO",
        "Cited in Google AI Summary after restructuring content for answer engines — removed JavaScript-hidden content, added plain-text questions, FAQ sections, answer-first summaries",
        "Achieved 1.8M organic impressions in month one via community-first content across Threads, Instagram, Rednote, TikTok",
        "Built an AI-powered content engine that transforms high-performing posts into blog posts and carousels",
        "Built an internal analytics dashboard to track conversion rates, cohort behaviour, and funnel performance",
        "Ran structured A/B tests on Meta ad creatives — isolated variables, tracked CPA by creative variant"
      ]
    },
    {
      "section": "Renmory — AEO / SEO Strategy",
      "bullets": [
        "Organic search is currently Renmory's second-largest inbound lead channel at 30%",
        "AEO strategy centred on query fan-out: identifying related questions AI search systems generate from broad prompts",
        "Research inputs: Google Search Console query data, \"people also search for\" results, social/forum discussions, repeated customer questions",
        "Content restructured for answer engines: direct answers at top, clear headers, FAQ sections, bullet points, tables, concise recommendations from actual product usage",
        "Original data from real wedding couples' question submissions and observed user behaviour (e.g., recommending 10–12 game questions and a 10–12 minute game length)",
        "Removed JavaScript-hidden question content and moved it into plain text so search and answer engines could parse it — after which Renmory was cited in Google AI Summary",
        "A salesperson from a large Taiwan wedding directory pitched a listing at NT$4,000 / A$177 per month — Benson chose to build compounding owned distribution instead"
      ]
    },
    {
      "section": "Renmory — B2B & Partnerships",
      "bullets": [
        "Designed and launched a B2B affiliate program targeting wedding consultants in Taiwan (promo codes, commission structure, partner-facing collateral)",
        "Ran cold outreach campaigns to wedding hosts and planners in Taiwan, Canada, and Hong Kong",
        "Created partner-facing marketing materials (flyers, landing pages, onboarding guides)"
      ]
    },
    {
      "section": "Renmory — Market Expansion",
      "bullets": [
        "Expanded from Taiwan into Singapore and Hong Kong, adapting product copy, onboarding flows, and marketing materials",
        "Managed bilingual product operations (English and Traditional Chinese), including localising cultural concepts — e.g., mapping 二進 (Taiwanese wedding ceremony) to \"reception\" for Western audiences"
      ]
    },
    {
      "section": "Mercer Investments — Process & Automation",
      "bullets": [
        "Built Python automations for reporting and trade execution workflows, reducing manual effort by 70% and saving 15+ hours monthly",
        "Proposed streamlined reporting workflow that reduced client reporting turnaround from 2 weeks to 2 business days",
        "Documented every automation with input/output specs, user guides, test results, and requirement specs for compliance team handoff",
        "Translated complex investment data into clear narratives for institutional stakeholders in quarterly reporting presentations",
        "Operated within a regulated institutional environment, ensuring all process changes met compliance, audit, and documentation standards"
      ]
    },
    {
      "section": "Grey Rhino",
      "bullets": [
        "Designed and launched an AI-powered SaaS MVP (Flask, React, SQL) for the Taiwanese education market",
        "Managed full product lifecycle from user research through delivery",
        "Conducted user research with Taiwanese educators to validate product assumptions"
      ]
    },
    {
      "section": "Sweetee",
      "bullets": [
        "Co-founded a couples relationship app with quiz card UI, colour systems, and React Native/Expo development",
        "Structured quiz content library of 276 questions across 36 themed quizzes",
        "Designed database schema and homepage mood-sharing feature"
      ]
    }
  ],
  "profileMd": {
    "archetypes": [
      {
        "name": "Growth Marketing",
        "axes": "Funnel optimisation, paid acquisition, SEO/AEO, content, experimentation",
        "whatTheyBuy": "Someone who already runs the full growth stack solo"
      },
      {
        "name": "Product Manager",
        "axes": "Product lifecycle, user research, rapid iteration, data-driven decisions",
        "whatTheyBuy": "Someone who's shipped products from zero and grown them"
      },
      {
        "name": "Growth Product Manager",
        "axes": "Growth + product intersection, conversion, activation, retention",
        "whatTheyBuy": "Someone who thinks in funnels AND features"
      },
      {
        "name": "Fintech Growth/Product",
        "axes": "Regulated environments, institutional finance + growth",
        "whatTheyBuy": "Someone who bridges finance and tech/growth"
      },
      {
        "name": "BDR / Sales",
        "axes": "Cold outreach, B2B partnerships, bilingual, pipeline building",
        "whatTheyBuy": "Someone who builds pipeline from scratch across markets"
      }
    ],
    "framingRules": [
      "Never say \"I haven't had time to do X.\" Reframe as \"I've done Y and it made me hungry to go deeper into X.\"",
      "Never lead with passion. Lead with proof that you already do it.",
      "Don't perform passion for the company's product. Show genuine interest in the growth *challenge*.",
      "Don't frame the job as training for future businesses. Frame as wanting disciplined growth at scale, with a team.",
      "Always include Mercer for fintech roles. It's the differentiator.",
      "One narrative per application. Lead with the skill that matches the role.",
      "\"I'm already living this role\" is the strongest opening. Use it."
    ],
    "compTargets": [
      {
        "roleType": "Junior/Associate Growth (AU)",
        "market": "National",
        "range": "A$90K minimum"
      },
      {
        "roleType": "Mid-level Growth Marketing (AU)",
        "market": "National",
        "range": "A$90K–120K"
      },
      {
        "roleType": "Associate Product Manager (AU)",
        "market": "Sydney",
        "range": "A$90K minimum"
      },
      {
        "roleType": "Growth/Marketing (Taiwan)",
        "market": "Taipei",
        "range": "NT$100,000/month minimum"
      },
      {
        "roleType": "Freelance growth consulting",
        "market": "Remote",
        "range": "A$500–800/day"
      }
    ]
  }
} as const;
