#!/usr/bin/env node
/**
 * codegen-states.mjs — single-source-of-truth state codegen (r8 fix)
 *
 * Reads templates/states.yml and generates:
 *   gen/states.json  — runtime-consumable JSON (Node scripts, dashboard)
 *   gen/states.js    — ESM module (import { STATES, LABELS, ALIASES } from '../gen/states.js')
 *   gen/states.go    — Go package for dashboard/internal
 *
 * Run: node scripts/codegen-states.mjs
 * CI:  npm run codegen && git diff --exit-code gen/
 *
 * Kills the r8 triplication: states.yml is the one place to add/rename states.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const srcPath  = path.join(ROOT, 'templates', 'states.yml');
const genDir   = path.join(ROOT, 'gen');
const jsonPath = path.join(genDir, 'states.json');
const jsPath   = path.join(genDir, 'states.js');
const goPath   = path.join(genDir, 'states.go');

// ── load source ──────────────────────────────────────────────────────────────

const raw = yaml.load(fs.readFileSync(srcPath, 'utf8'));
const states = raw.states;

if (!Array.isArray(states) || states.length === 0) {
  console.error('codegen: no states found in templates/states.yml');
  process.exit(1);
}

// ── gen/states.json ──────────────────────────────────────────────────────────

const jsonOut = JSON.stringify({ states }, null, 2) + '\n';
fs.mkdirSync(genDir, { recursive: true });
const jsonTmp = jsonPath + '.tmp';
fs.writeFileSync(jsonTmp, jsonOut, 'utf8');
fs.renameSync(jsonTmp, jsonPath);

// ── gen/states.js ─────────────────────────────────────────────────────────────

const statesArray = states.map(s => ({
  id:              s.id,
  label:           s.label,
  aliases:         s.aliases || [],
  description:     s.description || '',
  dashboard_group: s.dashboard_group || s.id,
}));

// Build lookup maps
const labelsObj  = Object.fromEntries(statesArray.map(s => [s.id, s.label]));
const aliasesObj = {};
for (const s of statesArray) {
  aliasesObj[s.id] = [s.label.toLowerCase(), ...s.aliases.map(a => a.toLowerCase())];
}

// Canonical set for fast membership test
const validIds = statesArray.map(s => s.id);

const jsOut = `// AUTO-GENERATED by scripts/codegen-states.mjs — DO NOT EDIT
// Source: templates/states.yml
// Regenerate: npm run codegen

export const STATES = ${JSON.stringify(statesArray, null, 2)};

/** Map of id → canonical label */
export const LABELS = ${JSON.stringify(labelsObj, null, 2)};

/** Map of id → [label, ...aliases] (all lowercase) */
export const ALIASES = ${JSON.stringify(aliasesObj, null, 2)};

/** All valid canonical IDs */
export const VALID_IDS = ${JSON.stringify(validIds)};

/**
 * Normalize a raw status string to a canonical id, or null if unrecognized.
 * Case-insensitive. Strips markdown bold (**).
 */
export function normalizeState(raw) {
  if (!raw) return null;
  const clean = raw.replace(/\\*\\*/g, '').trim().toLowerCase();
  for (const [id, variants] of Object.entries(ALIASES)) {
    if (variants.includes(clean)) return id;
  }
  return null;
}

/**
 * Return true if the string is a valid canonical id or recognized alias.
 */
export function isValidState(raw) {
  return normalizeState(raw) !== null;
}
`;

const jsTmp = jsPath + '.tmp';
fs.writeFileSync(jsTmp, jsOut, 'utf8');
fs.renameSync(jsTmp, jsPath);

// ── gen/states.go ─────────────────────────────────────────────────────────────

function goStringSlice(arr) {
  if (arr.length === 0) return '[]string{}';
  return `[]string{${arr.map(a => `"${a.replace(/"/g, '\\"')}"`).join(', ')}}`;
}

const goStateStructs = statesArray.map(s => `
	{
		ID:             "${s.id}",
		Label:          "${s.label}",
		Aliases:        ${goStringSlice(s.aliases)},
		Description:    "${s.description.replace(/"/g, '\\"')}",
		DashboardGroup: "${s.dashboard_group}",
	},`).join('');

const goOut = `// AUTO-GENERATED by scripts/codegen-states.mjs — DO NOT EDIT
// Source: templates/states.yml
// Regenerate: npm run codegen

package gen

// State represents a canonical application status.
type State struct {
	ID             string
	Label          string
	Aliases        []string
	Description    string
	DashboardGroup string
}

// States is the ordered list of all canonical states.
var States = []State{${goStateStructs}
}

// LabelByID returns the canonical label for a state ID, or "" if not found.
func LabelByID(id string) string {
	for _, s := range States {
		if s.ID == id {
			return s.Label
		}
	}
	return ""
}

// NormalizeState returns the canonical ID for a raw status string (case-insensitive,
// strips markdown bold), or "" if unrecognized.
func NormalizeState(raw string) string {
	import_strings_lower := func(s string) string {
		result := make([]byte, len(s))
		for i := 0; i < len(s); i++ {
			c := s[i]
			if c >= 'A' && c <= 'Z' {
				c += 32
			}
			result[i] = c
		}
		return string(result)
	}
	// strip **
	clean := raw
	for {
		idx := -1
		for i := 0; i < len(clean)-1; i++ {
			if clean[i] == '*' && clean[i+1] == '*' {
				idx = i
				break
			}
		}
		if idx == -1 {
			break
		}
		end := idx + 2
		clean = clean[:idx] + clean[end:]
	}
	clean = import_strings_lower(clean)
	// trim spaces
	for len(clean) > 0 && clean[0] == ' ' {
		clean = clean[1:]
	}
	for len(clean) > 0 && clean[len(clean)-1] == ' ' {
		clean = clean[:len(clean)-1]
	}
	for _, s := range States {
		if import_strings_lower(s.Label) == clean {
			return s.ID
		}
		for _, a := range s.Aliases {
			if import_strings_lower(a) == clean {
				return s.ID
			}
		}
	}
	return ""
}
`;

// Note: the Go file uses inline helper to avoid import — dashboard package
// already imports "strings" but gen is a standalone package. If dashboard
// integrates this, replace the inline helper with strings.ToLower.

const goTmp = goPath + '.tmp';
fs.writeFileSync(goTmp, goOut, 'utf8');
fs.renameSync(goTmp, goPath);

// ── summary ───────────────────────────────────────────────────────────────────

console.log(`codegen-states: generated from ${states.length} states`);
console.log(`  → ${path.relative(ROOT, jsonPath)}`);
console.log(`  → ${path.relative(ROOT, jsPath)}`);
console.log(`  → ${path.relative(ROOT, goPath)}`);
